github_checks:
  annotations: true

codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  status:
    project:
      default:
        enabled: yes
        # basic
        target: 60%
        threshold: 1%
        if_ci_failed: error #success, failure, error, ignore
        removed_code_behavior: off
    patch:
      default:
        enabled: off
        # basic
        target: 60%
        threshold: 1%
        if_ci_failed: error #success, failure, error, ignore
        removed_code_behavior: off
