# Go
# Build your Go project.
# Add steps that test, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/go
# SET UP GO
trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  goVersion: '1.20.1' # Go version

steps:
  - task: GoTool@0
    inputs:
      version: $(goVersion)

  - script: |
      echo "Check Go version"
      go version
    displayName: 'Go version'

  - script: |
      echo "Fetch Dependencies"
      go mod download
    displayName: 'Fetch dependencies'

  - script: |
      echo "Build"
      go build -v ./...
    displayName: 'Build'

  - task: CopyFiles@2
    inputs:
      Contents: '**'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'

  - script: |
      echo "Run Tests"
      go test -v ./...
    displayName: 'Run tests'