github_checks:
  annotations: true

codecov:
    notify:
        require_ci_to_pass: yes

coverage:
    precision: 2
    round: down
    range: "60...100"
    status:
      project:
        default:
          # basic
          target: 60%
          threshold: 1%
          base: 60%
          if_ci_failed: error #success, failure, error, ignore

      patch:
        default:
          # basic
          target: 60%
          threshold: 1%
          base: 60%
          if_ci_failed: error #success, failure, error, ignore